### ISSUE TITLE
感觉代码是不是没写完啊

### ISSUE THREAD

**Issue by LakersUpAma** [StanleyLsx/relation_extraction#1]
预测代码还有torch的，rematch函数好像也没声明？

**Comment by stanleylsx** [comment]
> 预测代码还有torch的，rematch函数好像也没声明？

还没

**Comment by LakersUpAma** [comment]
好的，谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StanleyLsx/relation_extraction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月11日(星期三) 上午9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [StanleyLsx/relation_extraction] 感觉代码是不是没写完啊 (Issue #1)





  
预测代码还有torch的，rematch函数好像也没声明？
  
还没
